on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install torch
          pip install pytest
          pip install tensorflow
  
      - name: Run pytest
        run: pytest
