on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: Run pytest
      run: pytest
