on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: Run pytest
      run: pytest test_ex1.py
